### ISSUE TITLE
Issue while training model

### ISSUE THREAD

**Issue by Godfather-Akshay** [JoshuaPiinRueyPan/ViolenceDetection#20]
Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Reading Training set...
Traceback (most recent call last):
  File "Train.py", line 196, in <module>
    main = Main()
  File "Train.py", line 16, in __init__
    self.trainer = Trainer(classifier)
  File "C:\Users\Akshay\Desktop\git\ViolenceDetection\src\Trainer.py", line 15, in __init__
    self._dataManager = TrainDataManager(dataSettings.PATH_TO_TRAIN_SET_CATELOG)
  File "C:\Users\Akshay\Desktop\git\ViolenceDetection\src\data\DataManager.py", line 226, in __init__
    LOADED_QUEUE_MAX_SIZE_=trainSettings.LOADED_QUEUE_MAX_SIZE)
  File "C:\Users\Akshay\Desktop\git\ViolenceDetection\src\data\DataManager.py", line 37, in __init__
    self._initVideoData(PATH_TO_DATA_SET_CATELOG_)
  File "C:\Users\Akshay\Desktop\git\ViolenceDetection\src\data\DataManager.py", line 82, in _initVideoData
    with open(PATH_TO_DATA_SET_CATELOG_, 'r') as fileContext:
FileNotFoundError: [Errno 2] No such file or directory: 'data/train.txt'
Exception ignored in: <bound method DataManagerBase.__del__ of <src.data.DataManager.TrainDataManager object at 0x0000021BF4620D68>>
Traceback (most recent call last):
  File "C:\Users\Akshay\Desktop\git\ViolenceDetection\src\data\DataManager.py", line 50, in __del__
    self.Stop()
  File "C:\Users\Akshay\Desktop\git\ViolenceDetection\src\data\DataManager.py", line 64, in Stop
    with self._lockForThreadControl:
AttributeError: 'TrainDataManager' object has no attribute '_lockForThreadControl'
Exception ignored in: <bound method Trainer.__del__ of <src.Trainer.Trainer object at 0x0000021B800A1D68>>
Traceback (most recent call last):
  File "C:\Users\Akshay\Desktop\git\ViolenceDetection\src\Trainer.py", line 39, in __del__
    self._dataManager.Stop()
AttributeError: 'Trainer' object has no attribute '_dataManager'
Exception ignored in: <bound method Main.__del__ of <__main__.Main object at 0x0000021BD9E30EF0>>
Traceback (most recent call last):
  File "Train.py", line 52, in __del__
    self.session.close()
AttributeError: 'Main' object has no attribute 'session'

**Comment by alaa-Mz** [comment]
Hello, 
i got the same issue, did you solve the issue??
