### ISSUE TITLE
when I run:python Train.py.I meet a problem,do you have some suggestions?

### ISSUE THREAD

**Issue by zhaowuyao** [JoshuaPiinRueyPan/ViolenceDetection#26]
.....................................................................
Reading Training set...
---------------------------------------------
---------------------------------------------
Video: /home/ViolenceDetection/dataset/yes/fi495_xvid.avi
Video: /home/ViolenceDetection/dataset/yes/fi379_xvid.avi
---------------------------------------------
Cannot find installation of real FFmpeg (which comes with ffprobe).
---------------------------------------------
Cannot find installation of real FFmpeg (which comes with ffprobe).
ignore the video because of the above error...
ignore the video because of the above error...
Video: /home/ViolenceDetection/dataset/yes/fi438_xvid.avi
Video: /home/ViolenceDetection/dataset/no/no255_xvid.avi
---------------------------------------------
Cannot find installation of real FFmpeg (which comes with ffprobe).
Cannot find installation of real FFmpeg (which comes with ffprobe).
---------------------------------------------
---------------------------------------------

ignore the video because of the above error...
---------------------------------------------
---------------------------------------------
Video: /home/ViolenceDetection/dataset/no/no318_xvid.avi
---------------------------------------------
Cannot find installation of real FFmpeg (which comes with ffprobe).
Video: /home/ViolenceDetection/dataset/yes/fi384_xvid.avi
Cannot find installation of real FFmpeg (which comes with ffprobe).
ignore the video because of the above error...
---------------------------------------------
Video: /home/ViolenceDetection/dataset/no/no249_xvid.avi
ignore the video because of the above error...
Cannot find installation of real FFmpeg (which comes with ffprobe).
---------------------------------------------
ignore the video because of the above error...
No image found in video: /home/ViolenceDetection/dataset/yes/fi379_xvid.avi,
Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images?  or is the video broken?
---------------------------------------------

Exception catched.  Put loadedVideos back to WaitingQueue and pass...
No image found in video: /home/ViolenceDetection/dataset/no/no255_xvid.avi,
Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images?  or is the video broken?No image found in video: /home//ViolenceDetection/dataset/yes/fi438_xvid.avi,
Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images?  or is the video broken?

Exception catched.  Put loadedVideos back to WaitingQueue and pass...

Exception catched.  Put loadedVideos back to WaitingQueue and pass...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/ViolenceDetection/src/data/DataManager.py", line 365, in _loadVideoData
    batchData.unrolledSize)
  File "/home/ViolenceDetection/src/data/DataManager.py", line 129, in _getDataFromSingleVideo
    arrayOfImages = video_.images[startFrameIndex_ : endFrameIndex]
  File "/home/ViolenceDetection/src/data/VideoData.py", line 53, in images
    + " before you try to access the images?  or is the video broken?")
ValueError: No image found in video: /home/ViolenceDetection/dataset/no/no255_xvid.avi,
Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images?  or is the video broken?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ViolenceDetection/src/data/DataManager.py", line 115, in runLoadingThread
    self._loadVideoData()
  File "/home/ViolenceDetection/src/data/DataManager.py", line 370, in _loadVideoData
    print("error occur at: b = ", b, ", currentVideo.images = ", currentVideo.images)
  File "/home/ViolenceDetection/src/data/VideoData.py", line 53, in images
    + " before you try to access the images?  or is the video broken?")
ValueError: No image found in video: /homeViolenceDetection/dataset/no/no255_xvid.avi,
Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images?  or is the video broken?

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/ViolenceDetection/src/data/DataManager.py", line 365, in _loadVideoData
    batchData.unrolledSize)
  File "/home/ViolenceDetection/src/data/DataManager.py", line 129, in _getDataFromSingleVideo
    arrayOfImages = video_.images[startFrameIndex_ : endFrameIndex]
  File "/home/ViolenceDetection/src/data/VideoData.py", line 53, in images
    + " before you try to access the images?  or is the video broken?")
ValueError: No image found in video: /home/ViolenceDetection/dataset/yes/fi438_xvid.avi,
Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images?  or is the video broken?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ViolenceDetection/src/data/DataManager.py", line 115, in runLoadingThread
    self._loadVideoData()
  File "/home/ViolenceDetection/src/data/DataManager.py", line 370, in _loadVideoData
    print("error occur at: b = ", b, ", currentVideo.images = ", currentVideo.images)
  File "/home/ViolenceDetection/src/data/VideoData.py", line 53, in images
    + " before you try to access the images?  or is the video broken?")
ValueError: No image found in video: /home/ViolenceDetection/dataset/yes/fi438_xvid.avi,
Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images?  or is the video broken?
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ViolenceDetection/src/data/DataManager.py", line 365, in _loadVideoData
    batchData.unrolledSize)
  File "/home/ViolenceDetection/src/data/DataManager.py", line 129, in _getDataFromSingleVideo
    arrayOfImages = video_.images[startFrameIndex_ : endFrameIndex]
  File "/home/ViolenceDetection/src/data/VideoData.py", line 53, in images
    + " before you try to access the images?  or is the video broken?")
ValueError: No image found in video: /home/ViolenceDetection/dataset/yes/fi495_xvid.avi,
Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images?  or is the video broken?

During handling of the above exception, another exception occurred:

tensorflow.python.framework.errors_impl.NotFoundError: temp/G2D19_P2OF_ResHB_1LSTM_dataAug_expLR; No such file or directory
Send Stop singal to Loading threads...
	 The Loading threads will Stop in about 100 (s).
Send Stop singal to Loading threads...
	 The Loading threads will Stop in about 100 (s).
	 TrainDataManager.thread.join() successfully.
Exception ignored in: <bound method Main.__del__ of <__main__.Main object at 0x7f6687efb898>>
Traceback (most recent call last):
  File "Train.py", line 52, in __del__
    self.session.close()
AttributeError: 'Main' object has no attribute 'session'

**Comment by harshavkumar** [comment]
This error is due to ffmpeg not installed.
Install ffmpeg on [windows ](https://m.wikihow.com/Install-FFmpeg-on-Windows) or [ubuntu](https://linuxize.com/post/how-to-install-ffmpeg-on-ubuntu-18-04)

**Comment by onkareshwarprasad17** [comment]
> ## .....................................................................
> Reading Training set...
> ## Video: /home/ViolenceDetection/dataset/yes/fi495_xvid.avi
> Video: /home/ViolenceDetection/dataset/yes/fi379_xvid.avi
> ## Cannot find installation of real FFmpeg (which comes with ffprobe).
> ## Cannot find installation of real FFmpeg (which comes with ffprobe).
> ignore the video because of the above error...
> ignore the video because of the above error...
> Video: /home/ViolenceDetection/dataset/yes/fi438_xvid.avi
> Video: /home/ViolenceDetection/dataset/no/no255_xvid.avi
> ## Cannot find installation of real FFmpeg (which comes with ffprobe).
> Cannot find installation of real FFmpeg (which comes with ffprobe).
> ## ignore the video because of the above error...
> ## Video: /home/ViolenceDetection/dataset/no/no318_xvid.avi
> ## Cannot find installation of real FFmpeg (which comes with ffprobe).
> Video: /home/ViolenceDetection/dataset/yes/fi384_xvid.avi
> Cannot find installation of real FFmpeg (which comes with ffprobe).
> ignore the video because of the above error...
> ## Video: /home/ViolenceDetection/dataset/no/no249_xvid.avi
> ignore the video because of the above error...
> Cannot find installation of real FFmpeg (which comes with ffprobe).
> ## ignore the video because of the above error...
> No image found in video: /home/ViolenceDetection/dataset/yes/fi379_xvid.avi,
> Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images? or is the video broken?
> Exception catched. Put loadedVideos back to WaitingQueue and pass...
> No image found in video: /home/ViolenceDetection/dataset/no/no255_xvid.avi,
> Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images? or is the video broken?No image found in video: /home//ViolenceDetection/dataset/yes/fi438_xvid.avi,
> Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images? or is the video broken?
> 
> Exception catched. Put loadedVideos back to WaitingQueue and pass...
> 
> Exception catched. Put loadedVideos back to WaitingQueue and pass...
> Exception in thread Thread-4:
> Traceback (most recent call last):
> File "/home/ViolenceDetection/src/data/DataManager.py", line 365, in _loadVideoData batchData.unrolledSize) File "/home/ViolenceDetection/src/data/DataManager.py", line 129, in _getDataFromSingleVideo arrayOfImages = video_.images[startFrameIndex_ : endFrameIndex]
> File "/home/ViolenceDetection/src/data/VideoData.py", line 53, in images
> + " before you try to access the images? or is the video broken?")
> ValueError: No image found in video: /home/ViolenceDetection/dataset/no/no255_xvid.avi,
> Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images? or is the video broken?
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
> self.run()
> File "/home/anaconda3/lib/python3.6/threading.py", line 864, in run
> self._target(*self._args, **self._kwargs)
> File "/home/ViolenceDetection/src/data/DataManager.py", line 115, in runLoadingThread
> self._loadVideoData()
> File "/home/ViolenceDetection/src/data/DataManager.py", line 370, in _loadVideoData
> print("error occur at: b = ", b, ", currentVideo.images = ", currentVideo.images)
> File "/home/ViolenceDetection/src/data/VideoData.py", line 53, in images
> + " before you try to access the images? or is the video broken?")
> ValueError: No image found in video: /homeViolenceDetection/dataset/no/no255_xvid.avi,
> Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images? or is the video broken?
> 
> Exception in thread Thread-3:
> Traceback (most recent call last):
> File "/home/ViolenceDetection/src/data/DataManager.py", line 365, in _loadVideoData batchData.unrolledSize) File "/home/ViolenceDetection/src/data/DataManager.py", line 129, in _getDataFromSingleVideo arrayOfImages = video_.images[startFrameIndex_ : endFrameIndex]
> File "/home/ViolenceDetection/src/data/VideoData.py", line 53, in images
> + " before you try to access the images? or is the video broken?")
> ValueError: No image found in video: /home/ViolenceDetection/dataset/yes/fi438_xvid.avi,
> Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images? or is the video broken?
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
> self.run()
> File "/home/anaconda3/lib/python3.6/threading.py", line 864, in run
> self._target(*self._args, **self._kwargs)
> File "/home/ViolenceDetection/src/data/DataManager.py", line 115, in runLoadingThread
> self._loadVideoData()
> File "/home/ViolenceDetection/src/data/DataManager.py", line 370, in _loadVideoData
> print("error occur at: b = ", b, ", currentVideo.images = ", currentVideo.images)
> File "/home/ViolenceDetection/src/data/VideoData.py", line 53, in images
> + " before you try to access the images? or is the video broken?")
> ValueError: No image found in video: /home/ViolenceDetection/dataset/yes/fi438_xvid.avi,
> Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images? or is the video broken?
> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "/home/ViolenceDetection/src/data/DataManager.py", line 365, in _loadVideoData batchData.unrolledSize) File "/home/ViolenceDetection/src/data/DataManager.py", line 129, in _getDataFromSingleVideo arrayOfImages = video_.images[startFrameIndex_ : endFrameIndex]
> File "/home/ViolenceDetection/src/data/VideoData.py", line 53, in images
> + " before you try to access the images? or is the video broken?")
> ValueError: No image found in video: /home/ViolenceDetection/dataset/yes/fi495_xvid.avi,
> Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images? or is the video broken?
> 
> During handling of the above exception, another exception occurred:
> 
> tensorflow.python.framework.errors_impl.NotFoundError: temp/G2D19_P2OF_ResHB_1LSTM_dataAug_expLR; No such file or directory
> Send Stop singal to Loading threads...
> The Loading threads will Stop in about 100 (s).
> Send Stop singal to Loading threads...
> The Loading threads will Stop in about 100 (s).
> TrainDataManager.thread.join() successfully.
> Exception ignored in: <bound method Main.**del** of <**main**.Main object at 0x7f6687efb898>>
> Traceback (most recent call last):
> File "Train.py", line 52, in **del**
> self.session.close()
> AttributeError: 'Main' object has no attribute 'session'

Have you solved your error "'Main' object has no attribute 'session'". If yes, then please share the info.
Thanks
