### ISSUE TITLE
queue.empty

### ISSUE THREAD

**Issue by Kevin35Day** [JoshuaPiinRueyPan/ViolenceDetection#3]
Hi,
GREAT JOB!

When I run Train.py , I kept meeting a  error.
 
Start Training...

Traceback (most recent call last):
Training terminate at epoch: 0 , steps: 0
  File "/home/stu/ViolenceDetection-master/src/data/DataManager.py", line 273, in AssignBatchData
	 Queue info = listOfData.len() = 421;	WaitingQueue.len() = 180;	LoadedQueue.len() = 0;	Pause = False
    timeout=dataSettings.TIMEOUT_FOR_WAIT_QUEUE)

  File "/home/stu/anaconda3/lib/python3.6/queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stu/ViolenceDetection-master/Train.py", line 198, in <module>
    main.Run()
  File "/home/stu/ViolenceDetection-master/Train.py", line 65, in Run
    self.trainer.PrepareNewBatchData()
  File "/home/stu/ViolenceDetection-master/src/Trainer.py", line 77, in PrepareNewBatchData
    raise error
  File "/home/stu/ViolenceDetection-master/src/Trainer.py", line 71, in PrepareNewBatchData
    self._dataManager.AssignBatchData(self._batchData)
  File "/home/stu/ViolenceDetection-master/src/data/DataManager.py", line 281, in AssignBatchData
    raise TimeoutError(errorMessage)
TimeoutError: In TrainDataManager:	 Unable to get batch data in duration: 100(s)
	 TrainQueue info:
listOfData.len() = 421;	WaitingQueue.len() = 180;	LoadedQueue.len() = 0;	Pause = False

It seems that the query is empty. Why? 
How can I solve this problem?
Thanks!

**Comment by JoshuaPiinRueyPan** [comment]
(Sorry for the late reply.  Looks like GitHub will not send me the e-mail while an issue is posted.)

What is your batch size?  If you set the batch size too large, the time to load all videos might exceed the waiting time of the main thread.

You can also edit the src/data/DataManager.py to set the 'IS_DEBUG_MODE = True'.  And paste the output here so that I can make sure if it's because of the batch size.

**Comment by heboyong** [comment]
I got the same error as you ,how you solve this problem?

**Comment by JoshuaPiinRueyPan** [comment]
Hi,
   Could you tell me the detail (such as how many cores of your CPU) of your computer?  And, what is your BATCH_SIZE in settings/TrainSettings.py?  This may be caused if the speed of the data loader too slow.  Normally, if you did not set the BATCH_SIZE too high (e.g. lower than '10'), this problem may not happend.
