### ISSUE TITLE
ValueError: No image found in the video.

### ISSUE THREAD

**Issue by onkareshwarprasad17** [JoshuaPiinRueyPan/ViolenceDetection#43]
I'm facing the below issue when I run the file "Train.py". I'm running this on google colab.
Need guidance and Kindly help. @JoshuaPiinRueyPan

Video: /content/drive/MyDrive/ViolenceDetection-master/dataset/NonViolence/football_crowds_cheering__Goldfellas_GT_vs_Maryland_1999_Crowd_Shot__tonyanddanielleoliva__xiCWDdaUSbg.avi

ignore the video because of the above error...
---------------------------------------------
Traceback (most recent call last):
  File "Train.py", line 198, in <module>
    main.Run()
  File "Train.py", line 84, in Run
    self.evaluateTestSetAndPrint(self.trainer.currentEpoch)
  File "Train.py", line 152, in evaluateTestSetAndPrint
    threshold_=self.bestThreshold)
  File "/content/drive/MyDrive/ViolenceDetection-master/src/Evaluator.py", line 43, in Evaluate
    currentLoss, correctPredictions = self._calculateValidationForSingleBatch(tf_session_)
  File "/content/drive/MyDrive/ViolenceDetection-master/src/Evaluator.py", line 90, in _calculateValidationForSingleBatch
    self._dataManager.AssignBatchData(batchData)
  File "/content/drive/MyDrive/ViolenceDetection-master/src/data/DataManager.py", line 492, in AssignBatchData
    self._frameCursor, unrolledSize)
  File "/content/drive/MyDrive/ViolenceDetection-master/src/data/DataManager.py", line 129, in _getDataFromSingleVideo
    arrayOfImages = video_.images[startFrameIndex_ : endFrameIndex]
  File "/content/drive/MyDrive/ViolenceDetection-master/src/data/VideoData.py", line 53, in images
    + " before you try to access the images?  or is the video broken?")
ValueError: No image found in video: /content/drive/MyDrive/ViolenceDetection-master/dataset/NonViolence/football_crowds_cheering__Goldfellas_GT_vs_Maryland_1999_Crowd_Shot__tonyanddanielleoliva__xiCWDdaUSbg.avi,
Do you forget to call 'VideoData.LoadVideoImages()' before you try to access the images?  or is the video broken?

**Comment by vanbou** [comment]
I also met this problem， how can I solve it

**Comment by QuantumHW** [comment]
Do you have this file  darknet19.pb？If so, can you share it? the link in the README is invalid
