### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by heboyong** [JoshuaPiinRueyPan/ViolenceDetection#7]
how can i solve this error:

Start Training...

Training terminate at epoch: 0 , steps: 0
	 Queue info = listOfData.len() = 61;	WaitingQueue.len() = 40;	LoadedQueue.len() = 0;	Pause = False

Traceback (most recent call last):
  File "D:\Desktop\ViolenceDetection\src\data\DataManager.py", line 271, in AssignBatchData
    timeout=dataSettings.TIMEOUT_FOR_WAIT_QUEUE)
  File "D:\python\lib\queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Desktop/ViolenceDetection/Train.py", line 197, in <module>
    main.Run()
  File "D:/Desktop/ViolenceDetection/Train.py", line 64, in Run
    self.trainer.PrepareNewBatchData()
  File "D:\Desktop\ViolenceDetection\src\Trainer.py", line 77, in PrepareNewBatchData
    raise error
  File "D:\Desktop\ViolenceDetection\src\Trainer.py", line 71, in PrepareNewBatchData
    self._dataManager.AssignBatchData(self._batchData)
  File "D:\Desktop\ViolenceDetection\src\data\DataManager.py", line 279, in AssignBatchData
    raise TimeoutError(errorMessage)
TimeoutError: In TrainDataManager:	 Unable to get batch data in duration: 30(s)
	 TrainQueue info:
listOfData.len() = 61;	WaitingQueue.len() = 40;	LoadedQueue.len() = 0;	Pause = False

**Comment by JoshuaPiinRueyPan** [comment]
Hi,
   I think the reason will be either the data loader too slow or your BATCH_SIZE too high.  You can use more threads to load the data, or lower the BATCH_SIZE.
   Also, I noticed that you might set the TIMEOUT_FOR_WAIT_QUEUE=30.  You can also enlarge the timeout to see if the data loader can provide the video on time.

**Comment by heboyong** [comment]
yeah,I have tried to run this model on another computer and it worked well ,so I think the reason of this error is small memory of GPU or CPU.Any way,thanks for your reply andyour job

**Comment by JoshuaPiinRueyPan** [comment]
Hi @heboyong ,
   I think it is the memory of the CPU.  It consume nearly 25GB/32GB main memory in my computer.  Your post remind me that I should consider the hardware capability of the ordinary devices while I set the default settings.  Thanks!

**Comment by hasnainnaeem** [comment]
@JoshuaPiinRueyPan First of all, thank you so much for putting in so much effort. Secondly, can you please tell me how I can change these settings? I have 16GB RAM and it uses almost 8-9 GB. I faced same error.

Also, this project is not using my GPU. I have tried most of the solutions available online. 

Lastly, do you have checkpoints trained on multiple datasets? For example on BEHAVE, Crowd Violence Detection & Real Life Violence Detection (Kaggle).
